INSERT INTO GENRE (NAME, CODE) VALUES ('Science fiction', 'SCIFI');
INSERT INTO GENRE (NAME, CODE) VALUES ('Horror', 'HOR');
INSERT INTO GENRE (NAME, CODE) VALUES ('Action and Adventure', 'ANA');
INSERT INTO GENRE (NAME, CODE) VALUES ('Mystery', 'MYS');
INSERT INTO GENRE (NAME, CODE) VALUES ('Fantasy', 'FAN');

INSERT INTO AUTHOR (FIRST_NAME, FAMILY_NAME) VALUES ('John R. R.', 'Tolkien');
INSERT INTO AUTHOR (FIRST_NAME, FAMILY_NAME) VALUES ('Bram', 'Stoker');
INSERT INTO AUTHOR (FIRST_NAME, FAMILY_NAME) VALUES ('Robert Louis', 'Stevenson');
INSERT INTO AUTHOR (FIRST_NAME, FAMILY_NAME) VALUES ('Douglas', 'Adams');

INSERT INTO BOOK (GENRE_ID, TITLE, ISBN, PUBLICATION_YEAR, NUMBER_OF_PAGES, PUBLISHER) VALUES (5, 'The Lord of the Rings', '0-395-08254-4', 1954,  9250, 'Allen & Unwin');

INSERT INTO BOOK_AUTHOR (BOOK_ID, AUTHOR_ID) VALUES (1, 1);